services:

  postgres:
    build: ./storage/postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    secrets:
      - postgres_user
      - postgres_password
      - postgres_db

    environment:
      POSTGRES_USER_FILE: /run/secrets/postgres_user
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_DB_FILE: /run/secrets/postgres_db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user) -d $(cat /run/secrets/postgres_db)"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./storage/images:/app/storage/images:Z
      # - backend_images:/app/storage/images

    secrets:
      - postgres_user
      - postgres_password
      - postgres_db
      - maptiler_apikey

    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      MAPTILER_API_KEY: /run/secrets/maptiler_apikey
      MAPTILER_STYLE_ID: /run/secrets/maptiler_style_id
      MAP_DEFAULT_ZOOM: ${MAP_DEFAULT_ZOOM:-5}
      MAP_WIDTH: ${MAP_WIDTH:-600}
      MAP_HEIGHT: ${MAP_HEIGHT:-400}
      MAP_FORMAT: ${MAP_FORMAT:-webp}
      MAP_IMAGE_QUALITY: ${MAP_IMAGE_QUALITY:-85}

    depends_on:
      postgres:
        condition: service_healthy

  adminer:
    image: adminer:latest
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

secrets:

  postgres_user:
    file: ./secrets/postgres_user.txt

  postgres_password:
    file: ./secrets/postgres_password.txt

  postgres_db:
    file: ./secrets/postgres_database.txt

  maptiler_apikey:
    file: ./secrets/maptiler_apikey.txt

  maptiler_style_id:
    file: ./secrets/maptiler_style_id.txt

volumes:
  postgres_data:
  # backend_images:
